Secure app from n+1 problems pull request
theresetuyi/Blog-app pull request #9
Opened 2023-08-28 21:38 UTC by theresetuyi

## Secure app from n+1 problems

- Secure app from n+1 problems.

2023-08-30 21:40 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Implemented some project requirements. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [OPTIONAL] Some of the previously written tests are failing. Kindly attend to them.

![prev-test-1](https://github.com/theresetuyi/Blog-app/assets/26597432/533e9588-9dd6-4e2d-a088-6adb8b49a86b)

![prev-tests-2](https://github.com/theresetuyi/Blog-app/assets/26597432/4658659e-7d56-4f7b-94b0-5a4ec5a527d3)
  

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 21:40 UTC, Qoosim commented on spec/models/integration/post_index_spec.rb
> +end
- [ ] Great job for implementing some some integration spec for the views. However, according to the project requirements, some tests are yet to be written. Kindly check below requirements and write their respective tests for them. 

### Project Requirements.
![post-index-rqts](https://github.com/theresetuyi/Blog-app/assets/26597432/7d6cdcc7-73f4-40ac-b2b1-aac02ff5583d)

2023-08-30 21:40 UTC, Qoosim commented on spec/models/integration/post_show_spec.rb
> +end
- [ ] Kindly complete the remaining test here too.

### Project requirements.
![post-show-rqt](https://github.com/theresetuyi/Blog-app/assets/26597432/1c2f3f43-e0e5-44f0-9541-dfeb80d07b9a)

2023-08-30 21:40 UTC, Qoosim commented on spec/models/integration/user_index_spec.rb
> +end
- [ ] Kindly complete the remaining test for this too.

### Project requirement

![user-index](https://github.com/theresetuyi/Blog-app/assets/26597432/89409739-21f9-4e8f-87a7-0d180a104b09)

2023-08-30 21:40 UTC, Qoosim commented on spec/models/integration/user_show_spec.rb
> +end
- [ ] This one too.

### Project requirement
![user-show](https://github.com/theresetuyi/Blog-app/assets/26597432/4df08fbc-40ad-4275-b500-fb6d0401425d)

2023-08-31 17:19 UTC, youmari approved these changes
# Project Approved :trophy: :tada: 🟢 

Hi @theresetuyi 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-09-01 09:08 UTC, merged